---
- name: install packages
  with_items: "{{ openhttpd_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart openhttpd

- name: create docroot
  file:
    path: /usr/local/www
    owner: www
    group: www
    state: directory

- name: create log dir
  file:
    path: /var/log/obhttpd
    state: directory

- name: enable service
  template:
    src: obhttpd.j2
    dest: /etc/rc.conf.d/obhttpd
  notify:
    - restart openhttpd
- name: create config dir
  file:
    path: /usr/local/etc/obhttpd.conf.d
    state: directory

- name: configure basics
  template:
    src: base.conf.j2
    dest: /usr/local/etc/obhttpd.conf.d/base.conf
  notify:
    - restart openhttpd

- stat: path=/usr/local/etc/obhttpd.conf.d/domains.conf
  register: domain_config

- name: configure domains
  template:
    src: domains.conf.j2
    dest: /usr/local/etc/obhttpd.conf.d/domains.conf
  notify:
    - restart openhttpd
  when: domain_config.stat.exists == False

- name: configure service
  template:
    src: obhttpd.conf.j2
    dest: /usr/local/etc/obhttpd.conf
  notify:
    - restart openhttpd
